<html>
<body bgcolor="pink">
<center><h1><a href="index1.html">back to home page...</a></h1></center>
<b><h1><mark>Introduction</mark></h1></b>
<p><b><u>COMPUTER ENGINEERING</u></b> is a branch of engineering that integrates several fields of computer science and electronic engineering required to develop computer hardware and software. Computer engineers usually have training in electronic engineering (or electrical engineering), software design, and hardware–software integration instead of only software engineering or electronic engineering. Computer engineers are involved in many hardware and software aspects of computing, from the design of individual microcontrollers, microprocessors, personal computers, and supercomputers, to circuit design. This field of engineering not only focuses on how computer systems themselves work, but also how they integrate into the larger picture.</p>

<p>Usual tasks involving computer engineers include writing software and firmware for embedded microcontrollers, designing VLSI chips, designing analog sensors, designing mixed signal circuit boards, and designing operating systems. Computer engineers are also suited for robotics research, which relies heavily on using digital systems to control and monitor electrical systems like motors, communications, and sensors.</p>

<p>In many institutions of higher learning, computer engineering students are allowed to choose areas of in-depth study in their junior and senior year because the full breadth of knowledge used in the design and application of computers is beyond the scope of an undergraduate degree. Other institutions may require engineering students to complete one or two years of general engineering before declaring computer engineering as their primary focus</p>

<b><h1><mark>History</mark></h1></b>
<p><b>Computer engineering</b> began in <b>1939</b> when <b>John Vincent Atanasoff</b> and <b>Clifford Berry</b> began developing the world's first electronic digital computer through physics, mathematics, and electrical engineering. <b>John Vincent Atanasoff</b> was once a physics and mathematics teacher for Iowa State University and <b>Clifford Berry</b> a former graduate under electrical engineering and physics. Together, they created the <b>Atanasoff-Berry computer</b>, also known as the ABC which took 5 years to complete.While the original ABC was dismantled and discarded in the <b>1940s</b> a tribute was made to the late inventors, a replica of the ABC was made in <b>1997</b> where it took a team of researchers and engineers four years and <b>$350,000 </b>to build.</p>

<b><h1><mark>History of Computer Engineering Education</b></h1></mark>
<p>The first computer engineering degree program in the United States was established in <b>1971</b> at Case Western Reserve University in Cleveland, Ohio. As of 2015, there were 250 ABET-accredited computer engineering programs in the U.S. In Europe, accreditation of computer engineering schools is done by a variety of agencies part of the EQANIE network. Due to increasing job requirements for engineers who can concurrently design hardware, software, firmware, and manage all forms of computer systems used in industry, some tertiary institutions around the world offer a bachelor's degree generally called computer engineering. Both computer engineering and electronic engineering programs include analog and digital circuit design in their curriculum. As with most engineering disciplines, having a sound knowledge of mathematics and science is necessary for computer engineers.</p>

<b><h1><mark>Education</b></h1></mark>
<p><b>Computer engineering</b> is referred to as computer science and engineering at some universities. Most entry-level computer engineering jobs require at least a bachelor's degree in computer engineering (or computer science and engineering). Typically one must learn an array of mathematics such as calculus, algebra and trigonometry and some computer science classes. Sometimes a degree in electronic engineering is accepted, due to the similarity of the two fields. Because hardware engineers commonly work with computer software systems, a strong background in computer programming is necessary. According to BLS, <b><u>"a computer engineering major is similar to electrical engineering but with some computer science courses added to the curriculum".</u></b> Some large firms or specialized jobs require a master's degree.</p>

<p>It is also important for computer engineers to keep up with rapid advances in technology. Therefore, many continue learning throughout their careers. This can be helpful, especially when it comes to learning new skills or improving existing ones. For example, as the relative cost of fixing a bug increases the further along it is in the software development cycle, there can be greater cost savings attributed to developing and testing for quality code as soon as possible in the process, and particularly before release.</p>
</body>
</html>