<html>
<body bgcolor="pink">
<center><h1><a href="index1.html">back to home page...</a></h1></center>
<b><h1><mark>Introduction</mark></h1></b>

<p><b><u>Science </u></b><u>(from the Latin word scientia, meaning "knowledge")</u> is a systematic enterprise that builds and organizes knowledge in the form of testable explanations and predictions about the universe.</p>

<p>The earliest roots of science can be traced to Ancient Egypt and Mesopotamia in around <b>3500</b> to <b>3000</b> BCE.Their contributions to mathematics, astronomy, and medicine entered and shaped Greek natural philosophy of classical antiquity, whereby formal attempts were made to explain events of the physical world based on natural causes.After the fall of the Western Roman Empire, knowledge of Greek conceptions of the world deteriorated in Western Europe during the early centuries <u>(400 to 1000 CE)</u> of the Middle Ages but was preserved in the Muslim world during the Islamic Golden Age.The recovery and assimilation of Greek works and Islamic inquiries into Western Europe from the 10th to 13th century revived natural philosophy,which was later transformed by the Scientific Revolution that began in the 16th century as new ideas and discoveries departed from previous Greek conceptions and traditions.The scientific method soon played a greater role in knowledge creation and it was not until the 19th century that many of the institutional and professional features of science began to take shape.</p>

<p>Modern science is typically divided into three major branches that consist of the natural sciences (e.g., biology, chemistry, and physics), which study nature in the broadest sense; the social sciences (e.g., economics, psychology, and sociology), which study individuals and societies; and the formal sciences (e.g., logic, mathematics, and theoretical computer science), which study abstract concepts. There is disagreement,however, on whether the formal sciences actually constitute a science as they do not rely on empirical evidence.Disciplines that use existing scientific knowledge for practical purposes, such as engineering and medicine, are described as applied sciences.</p>

<p>Science is based on research, which is commonly conducted in academic and research institutions as well as in government agencies and companies. The practical impact of scientific research has led to the emergence of science policies that seek to influence the scientific enterprise by prioritizing the development of commercial products, armaments, health care, and environmental protection.</p>


<b><h1><mark>History</b></h1></mark>
<h7>Main article: History of science</h7>
<p>Science in a broad sense existed before the modern era and in many historical civilizations. Modern science is distinct in its approach and successful in its results, so it now defines what science is in the strictest sense of the term.Science in its original sense was a word for a type of knowledge, rather than a specialized word for the pursuit of such knowledge. In particular, it was the type of knowledge which people can communicate to each other and share. For example, knowledge about the working of natural things was gathered long before recorded history and led to the development of complex abstract thought. This is shown by the construction of complex calendars, techniques for making poisonous plants edible, public works at national scale, such as those which harnessed the floodplain of the Yangtse with reservoirs, dams, and dikes, and buildings such as the Pyramids. However, no consistent conscious distinction was made between knowledge of such things, which are true in every community, and other types of communal knowledge, such as mythologies and legal systems. Metallurgy was known in prehistory, and the Vinča culture was the earliest known producer of bronze-like alloys. It is thought that early experimentation with heating and mixing of substances over time developed into alchemy.</p>

<b><h1><mark>Branches of science</b></h1></mark>
<h7>Main article: Branches of science</h7>
<p>Modern science is commonly divided into three major branches that consist of the natural sciences, social sciences, and formal sciences. Each of these branches comprise various specialized yet overlapping scientific disciplines that often possess their own nomenclature and expertise.Both natural and social sciences are empirical sciences as their knowledge are based on empirical observations and are capable of being tested for its validity by other researchers working under the same conditions.There are also closely related disciplines that use science, such as engineering and medicine.</p>

<b><h1><mark>Natural science</b></h1></mark>
<h7>Main articles: Natural science and Outline of natural science</h7>

<p>False-color composite of global oceanic and terrestrial photoautotroph abundance by the SeaWiFS Project, NASA/Goddard Space Flight Center, and ORBIMAGE.
Natural science is concerned with the description, prediction, and understanding of natural phenomena based on empirical evidence from observation and experimentation. It can be divided into two main branches: life science (or biological science) and physical science. Physical science is subdivided into branches, including physics, chemistry, astronomy and earth science. These two branches may be further divided into more specialized disciplines. Modern natural science is the successor to the natural philosophy that began in Ancient Greece. Galileo, Descartes, Bacon, and Newton debated the benefits of using approaches which were more mathematical and more experimental in a methodical way. Still, philosophical perspectives, conjectures, and presuppositions, often overlooked, remain necessary in natural science.Systematic data collection, including discovery science, succeeded natural history, which emerged in the 16th century by describing and classifying plants, animals, minerals, and so on.Today, <b>"natural history" </b>suggests observational descriptions aimed at popular audiences.</p>

<b><h1><mark>Social science</b></h1></mark>
<h7>Main articles: Social science and Outline of social science</h7>

<p>In economics, the supply and demand model describes how prices vary as a result of a balance between product availability and demand.
Social science is concerned with society and the relationships among individuals within a society. It has many branches that include, but are not limited to, anthropology, archaeology, communication studies, economics, history, human geography, jurisprudence, linguistics, political science, psychology, public health, and sociology. Social scientists may adopt various philosophical theories to study individuals and society. For example, positivist social scientists use methods resembling those of the natural sciences as tools for understanding society, and so define science in its stricter modern sense. Interpretivist social scientists, by contrast, may use social critique or symbolic interpretation rather than constructing empirically falsifiable theories, and thus treat science in its broader sense. In modern academic practice, researchers are often eclectic, using multiple methodologies <b><u>(for instance, by combining both quantitative and qualitative research)</u></b>. The term <b>"social research"</b> has also acquired a degree of autonomy as practitioners from various disciplines share in its aims and methods.</p>

<b><h1><mark>Formal science</b></h1></mark>
<h7>Main articles: Formal science and Outline of formal science</h7>

<p>A humanoid robotic hand (see Shadow Hand system).
Formal science is involved in the study of formal systems. It includes mathematics, systems theory, robotics, and theoretical computer science. The formal sciences share similarities with the other two branches by relying on objective, careful, and systematic study of an area of knowledge. They are, however, different from the empirical sciences as they rely exclusively on deductive reasoning, without the need for empirical evidence, to verify their abstract concepts.The formal sciences are therefore a priori disciplines and because of this, there is disagreement on whether they actually constitute a science.Nevertheless, the formal sciences play an important role in the empirical sciences. Calculus, for example, was initially invented to understand motion in physics.Natural and social sciences that rely heavily on mathematical applications include mathematical physics, mathematical chemistry, mathematical biology, mathematical finance, and mathematical economics.</p>
</body>
</html